### ISSUE TITLE
Cannot run `make_report_descriptive.py` due to missing data.

### ISSUE THREAD

**Issue by bishax** [nestauk/sg_covid_impact#92]
```
Traceback (most recent call last):
  File "sg_covid_impact/make_report_descriptive.py", line 85, in <module>
    exposures_ranked, keyword_weights = calculate_sector_exposure()
  File "/home/alex/GIT/scotland-covid/sg_covid_impact/descriptive.py", line 371, in calculate_sector_exposure
    term_salience = read_salience()
  File "/home/alex/GIT/scotland-covid/sg_covid_impact/descriptive.py", line 80, in read_salience
    with open(f"{project_dir}/data/processed/salient_words_division.p", "rb") as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/alex/GIT/scotland-covid/data/processed/salient_words_division.p'
```
I can't find anywhere in the code where `data/processed/salient_words_division.p` is created.

**Comment by bishax** [comment]
Closed by #73
